### ISSUE TITLE
Ora din atasamentul de calendar la confirmare rezervare e cu 3h in urma

### ISSUE THREAD

**Issue by victorbucutea** [victorbucutea/parking-space#100]

**Comment by ovidiu16** [comment]
Oare puteti sa-mi dati si atasamentul sau mai multe detalii? Nu prea inteleg bug-ul.

**Comment by victorbucutea** [comment]
E un atasament la fiecare mail cu un calendar entry. Pe mobile ar tb sa
sigereze sa adaugi evenimentul in calendar. Reservation.ics se numeste


mar., 14 iul. 2020, 8:39 PM Cimpan Ovidiu <notifications@github.com> a
scris:

**Comment by ovidiu16** [comment]
Este ok pe mobile si desktop.
![Rezc](https://user-images.githubusercontent.com/33632578/87463007-75240b80-c619-11ea-8bae-ff1c54f2a010.png)
![109513465_300093227702416_6457316583563330497_n](https://user-images.githubusercontent.com/33632578/87463009-75bca200-c619-11ea-9389-f7b863f24bb4.jpg)
