### ISSUE TITLE
Platile efectuate nu sunt convertite euro, dolari,etc

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#103]
1.Posteaza un loc de parcare in euro sau in orice inafara de lei
2.Rezerva locul
3.Observa banii in plati efectuate, Sold disponibil, mail si mesaj

Observat
Am facut o rezervare de 317 euro (240 fara taxe) si apare in lei peste tot, in afara de contul care a primit plata (la plati primite apare 240 eur).

Asteptat
Banii ar trebui sa fie convertiti automat in lei si sa apara suma reala. (240 euro = 1.161,55 RON)
![Banimail](https://user-images.githubusercontent.com/33632578/87250768-f2ac1800-c46f-11ea-82b6-1b449cc6959c.png)
![Baniron](https://user-images.githubusercontent.com/33632578/87250771-f3dd4500-c46f-11ea-86cd-7bcf150d5117.png)
![Banieur](https://user-images.githubusercontent.com/33632578/87250773-f3dd4500-c46f-11ea-9dd1-8c0f4dbfe7fa.png)

**Comment by victorbucutea** [comment]
Am blocat sa se poata fface postari doar in Ron. Cand vom incepe si in alta tara, reluam issue-ul :)

**Comment by ovidiu16** [comment]
Fixat.
![rons](https://user-images.githubusercontent.com/33632578/87463431-0b583180-c61a-11ea-94c4-c47fc32f75cc.png)
