### ISSUE TITLE
Link-urile sunt prea mari

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#106]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search/post
2.Click pe Vinde

Observat
Link-urile "Alege pe harta" si "Orar pe zile / ore" pot fi apasate si inafara textului.

Asteptat
Link-urile ar trebui sa poata fi apasate doar pe text (Alege pe harta si Orar pe zile/ore)
![Link](https://user-images.githubusercontent.com/33632578/87460304-53c12080-c615-11ea-830a-e6a97aface43.png)

**Comment by victorbucutea** [comment]
E ok asa, Creste utilizabilitatea pe mobil . E drept ca poti face. tap din greseala, dar cat de des ti ss-a intamplat?

**Comment by ovidiu16** [comment]
Am dat de cateva ori din greseala click pe link-uri.
Daca un utilizator nu intra foarte des si nu pune foarte multe locuri de parcare, nu cred ca este o problema.
