### ISSUE TITLE
Euro in loc de Ron

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#108]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe Locurile mele si observa sectiunea "Ati castigat in total"

Observat
Apare Eur si mai jos in sectiunea "Aveti in cont" apare Ron.
Dupa reincarcarea paginii, apare Ron in loc de Eur.

Asteptat
Ron ar trebui sa apara peste tot.
![EUr](https://user-images.githubusercontent.com/33632578/88397445-95e42200-cdcc-11ea-9668-ba14e24bcec4.png)

**Comment by victorbucutea** [comment]
E posibil as fi fost ca in cache era versiunea veche de javacript. Se mai reproduce acum ? M-am logat cu ovidiu.ovidiu+11@gmail.com si nu il reproduc

**Comment by ovidiu16** [comment]
Nu se mai reproduce.
