### ISSUE TITLE
Sold disponibil prea mare

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#109]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/account/payments-received
2.Observa Soldul disponibil

Observat
La sold disponibil apar 2151.80 Ron si la Plati primite 240 Ron

Asteptat
La Sold disponibil ar trebui sa fie doar 240 Ron daca atat apare la Plati primite.

Testat cu ovidiu.ovidiu0+50@gmail.com
Pass: Test1234!
![Platass](https://user-images.githubusercontent.com/33632578/88485447-6a089e00-cf7e-11ea-8bb1-97ec0b306f14.png)

**Comment by victorbucutea** [comment]
Ovidiu bug-ul asta se datoreaza solduriloor ramse de pana acum diainte de toate fix-urile. 
Va tb testat cu un utilizator nou din pacate.

**Comment by victorbucutea** [comment]
Partea tb testata bine, insa cu un set nou de utilizatori.

**Comment by ovidiu16** [comment]
Am folosit doua conturi noi si problema s-a rezolvat.
![Solds](https://user-images.githubusercontent.com/33632578/89565566-6bac4e80-d827-11ea-954b-64091c88ab61.png)
