### ISSUE TITLE
Rezevare facuta in trecut

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#11]
Observat
Am reușit sa fac o rezervare în trecut.
Ora a fost 4:29 pm  și am făcut rezervare de la 4:00 pm la 4:30 pm

Așteptat
Ora nu ar trebui sa poata fi aleasa in trecut.

![Timp](https://user-images.githubusercontent.com/33632578/84599469-fc475d80-ae7a-11ea-9206-14c505f8a013.png)

**Comment by victorbucutea** [comment]
ok, I will put this in fixed once it's deployed

**Comment by ovidiu16** [comment]
Fixat.
![Trecut](https://user-images.githubusercontent.com/33632578/84699140-aeeded80-af59-11ea-9af2-d68f46f13674.png)
