### ISSUE TITLE
Rezervare trecuta in cont nou

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#12]
Observat
Pe un cont nou creat era o rezervare trecuta.

Așteptat
Un cont nou creat nu ar trebui sa aibă o rezervare trecuta.

![RezervareTrecuta](https://user-images.githubusercontent.com/33632578/84599958-85ac5f00-ae7e-11ea-9d8d-0ed334120844.png)

**Comment by victorbucutea** [comment]
E un test case bun, insa din punctul meu de vedere orice rezervare in plus inseamna revenue. 
Daca cineva vrea sa regleze un cont cu o rezervare in trecut, nu-i nici o pb. 

Din punct de vedere integritate a datelor nu ridica o pb.
