### ISSUE TITLE
Stelele de review ar trebui sa fie de acceasi culoare

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#13]
1.Apăsați pe un loc de parcare disponibil
2.Observați stelele de review din partea stânga a hărții și stelele de pe modal de la locul de parcare

Observat
Secțiunea "Opinia clienților" din partea stânga a hărții are stelele în culoarea gri și paranteze rotunde.
Secțiunea de review de pe modalul de parcare are stelele in culoarea galben si in paranteze rotunde are "0 reviews"

Așteptat
Cele doua secțiuni ar trebui sa aibă stelele în culoare gri daca nu sunt reviews si galbene daca sunt reviews. In paranteze ar trebui sa scrie cate reviews sunt. 

![Reviews](https://user-images.githubusercontent.com/33632578/84600267-c6a57300-ae80-11ea-8e92-6c9c1c8dd532.png)

**Comment by victorbucutea** [comment]
am rugamintea sa pui milestone-ul v1.0 ;) . Target-ul e sa livram versiunea asta pana la 30 Iunie.

**Comment by ovidiu16** [comment]
Nu am acces la partea din dreapta - Labels, Projects, Milestone.
Pot sa editez doar titlul si commentul.
Imi trebuie ceva acces special sau nu fac ceva bine?

**Comment by ovidiu16** [comment]
Fixat.
![Opinie](https://user-images.githubusercontent.com/33632578/84698979-60d8ea00-af59-11ea-97a4-8ee0b0700fc7.png)
