### ISSUE TITLE
Butonul de "Plateste acum" este vizibil la o rezervare trecuta

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#14]
Asteptat
Butonul de "Plateste acum" nu ar mai trebui sa fie vizibil la o rezervare trecuta.

![PlatesteOn](https://user-images.githubusercontent.com/33632578/84600369-5a773f00-ae81-11ea-91b5-c03de7664982.png)

**Comment by victorbucutea** [comment]
Asta e ok asa. Poate cineva a plecat de pe locul de parcare si va vrea sa il plateasca ulterior. Why not.
