### ISSUE TITLE
Bani in cont fara a vinde un loc de parcare

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#17]
https://go-park-staging.herokuapp.com/app/index.html#!/account/payments

Observat
Pe un cont nou creat cu doua rezervări făcute, în cont sunt 50 Ron.

Așteptat
Banii în cont ar trebui sa apară doar în momentul în care utilizatorul are un loc de parcare și a fost rezervat cel puțin odată.
![Ron](https://user-images.githubusercontent.com/33632578/84600913-711f9500-ae85-11ea-9349-a8273e44527b.png)

**Comment by victorbucutea** [comment]
Cum ai reusit? Doar facand rezervari se adauga bani in cont? 

Am nevoie de mai multi pasi pentru a reproduce .

**Comment by ovidiu16** [comment]
Bug-ul inca exista.
Am folosit RO49AAAA1B31007593840000 pentru IBAN.
Suma de transfer a fost cu minus ( -87 ), am apasat pe butonul "Retrage", am reincarcat pagina si balanta a fost actualizata cu 87 cant a pus eu cu minus.

Campul "Suma transfer" nu ar trebui sa lase utilizatorul sa puna o suma cu minus.
![ezgif-2-90ebd5e94b75](https://user-images.githubusercontent.com/33632578/84700891-a8ad4080-af5c-11ea-883b-372ed61cd122.gif)

**Comment by ovidiu16** [comment]
Fixat.
