### ISSUE TITLE
Formatul campurilor email si parola in pagina de Login

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#18]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/login?fbLogin=user_denied
2.Adauga in campul email "t@t", iar in campul parola" " (Spatiu gol)

Observat
Campul email valideaza "t@t" ca si email valid, iar campul parola valideaza un spatiu gol.

Asteptat
Formatul emailului ar trebui sa fie "text@text.text"
Parola ar trebui sa fie validata adaugand caractere alfanumerice si/sau caractere speciale. (Ar fi ok daca ar fi si o limita minima de caractere)
![login](https://user-images.githubusercontent.com/33632578/84692623-d8ede280-af4e-11ea-93df-36d1bc60a9e6.png)

**Comment by victorbucutea** [comment]
Ok, se pare ca t@t e un email valid, asa cum valideaza browser-ul un input de tipul email in HTML5. Am pus un regex sa fie mai friendly.

Cu privire la parola aici o sa pun o lungime minima de 5-6 caracter , insa validarea adevarata ar tb sa se faca la inregistrare ( cred ca acolo nu e impus sa contina semne :? ,etc. )

**Comment by ovidiu16** [comment]
Fixat.
![Log](https://user-images.githubusercontent.com/33632578/84819790-44a08000-b021-11ea-9ee8-43750c78d8a7.png)
