### ISSUE TITLE
"User denied" este afisat cand utilizatorul acceseaza pagina de "Intra in cont"

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#20]
1.Acceseaza https://go-park-staging.herokuapp.com/
2.Click pe "Intra in cont"

Observat
Eroarea "Pentru a putea accesa aplicația te rugăm să te autentifici." este afisata in momentul in care utilizatorul intra pe pagina de Login.

Asteptat
Eroarea nu ar trebui sa fie afisata din moment ce utilizatorul da click pe butonul de "Intra in cont" si doreste sa se logheze.
![ezgif-2-292fa072ab63](https://user-images.githubusercontent.com/33632578/84694082-413dc380-af51-11ea-8d76-d317830b2a97.gif)

**Comment by victorbucutea** [comment]
Ok. Am fixat de testat ca eroarea apare  in cazul expirarii sesiunii ( poti simula dand logout din alt tab de browser. )

**Comment by ovidiu16** [comment]
Eroarea nu mai apare cand utilizatorul da click pe butonul "Intra in cont", apare doar in momentul in care utilizatorul da click pe log out.
