### ISSUE TITLE
Paginile "Harta", "Locurile mele" si "Rezervari" sunt afisate pentru putin timp 

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#23]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/login?fbLogin=user_denied
2.Click pe paginile  "Harta", "Locurile mele" si "Rezervari"

Observat
Paginile sunt afisate pentru putin timp.

Asteptat
Paginile nu ar trebui sa fie afisate daca utilizatoul nu este logat.
![ezgif-2-ed556a984386](https://user-images.githubusercontent.com/33632578/84695531-9da1e280-af53-11ea-8232-dda79ed30485.gif)

**Comment by victorbucutea** [comment]
Bug-ul asta face parte dintr-un task mai complicat. Nu as vrea sa intru iar acolo ca ma tem ca stric altceva. Il punem in won't fix pt moment.
