### ISSUE TITLE
Video si Gif in loc de poza 

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#27]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Click pe "Incarca o poza cu masina" si incarca un video sau Gif sub 8 mb

Observat
Am reusit sa incarc un video, Gif, PDF si aplicatie sub 8mb in loc de poza.

Asteptat
Utilizatorul ar trebui sa poata sa incarce doar poze.
![ezgif-2-b50aedcde8a1](https://user-images.githubusercontent.com/33632578/84698314-45b9aa80-af58-11ea-9c0c-563cb95c5bf8.gif)

**Comment by victorbucutea** [comment]
Daca asta e singurul bug in pagina de autentificare, atunci suntem bine :)

**Comment by ovidiu16** [comment]
Bug-ul inca exista.
![Incarc](https://user-images.githubusercontent.com/33632578/84821808-60f1ec00-b024-11ea-8293-afd74aa6f90d.png)

**Comment by victorbucutea** [comment]
Pe ce browser incerci? Am incercat pe safari si chrome si astea par sa respecte tipul fisierului. Nevertheless Problema cu multiple uploads sper sa se fi rezolvat. De testat pe mai multe browsere inclusiv mobile

**Comment by ovidiu16** [comment]
Pe Firefox 77 am testat.

**Comment by victorbucutea** [comment]
nu testa inca, ca acum se deployeaza. Vedem maine.

**Comment by ovidiu16** [comment]
Nu se mai pot adauga mai multe fisiere, dar tot se pot adauga gif-uri, documente, programe sub 8mb.
Testat pe Firefox 77 si Chrome pe mobil.
![Add](https://user-images.githubusercontent.com/33632578/85060322-bc9bb100-b1ad-11ea-9406-5c50305f4aca.png)

**Comment by victorbucutea** [comment]
ook hai sa mai incercam si varianta asta. Mai jos testul pe FF. nu ma lasa sa adaug un alt timp de fisier
<img width="445" alt="Screenshot 2020-06-21 at 22 26 31" src="https://user-images.githubusercontent.com/1927369/85233375-5497d580-b40e-11ea-8685-e9aee6b2ddad.png">

**Comment by ovidiu16** [comment]
Pe Windows se pare ca se pot adauga orice fel de fisiere mai mici de 8mb.
Testat pe Chrome 83 si Firefox 77.
![Chrome](https://user-images.githubusercontent.com/33632578/85324285-3abfc680-b4d2-11ea-888e-01a681abd69e.png)

**Comment by victorbucutea** [comment]
Ok, am pus inca o verificare la incarcarea fisierului.

**Comment by ovidiu16** [comment]
Fixat.
![Incarcs](https://user-images.githubusercontent.com/33632578/86956306-8d9bae00-c161-11ea-833f-28339fc9ff21.png)
