### ISSUE TITLE
United States of America este duplicat 

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#28]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Click pe butonul alege tara si deruleaza pana la USA

Observat
United States of America este duplicat, iar dand click pe primul USA din lista, apare in campul telefon doar "e.g."

Asteptat
Doar un rezultat de USA ar trebui sa apara in lista, iar pe campul telefon ar trebui sa apara "e.g. 201 555 1234"
![USA](https://user-images.githubusercontent.com/33632578/84808558-80334e00-b011-11ea-8a18-d1e3e009a88c.png)

**Comment by ovidiu16** [comment]
Problema inca exista.
Testat pe Firefox 77, Chrome 83 si Chrome mobile.
![USA](https://user-images.githubusercontent.com/33632578/85060669-4cd9f600-b1ae-11ea-8f58-7d73351415ca.png)

**Comment by victorbucutea** [comment]
Dap .. nu am redeployat inca. Oricum va tb sa inchizi si sa redeschizi browser-ul ca sa isi refaca cache-ul.

**Comment by victorbucutea** [comment]
Incearca inca o data. acum am scos din parametrii duplicatul

**Comment by ovidiu16** [comment]
Fixat.
![US](https://user-images.githubusercontent.com/33632578/85231893-a5560100-b403-11ea-88a4-2689d9e62f46.png)
