### ISSUE TITLE
Campurile valideaza spatiu gol

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#29]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Adauga spatii goale in campurile "Nr. inmatriculare", "Nume si prenume" si "Parola"

Asteptat
Campurile nu ar trebui sa valideze spatii goale,
![Fields](https://user-images.githubusercontent.com/33632578/84809575-de146580-b012-11ea-8cfc-39aa1929576b.png)

**Comment by ovidiu16** [comment]
Problema inca exista.
Testat pe Firefox 77 private.
![Valid](https://user-images.githubusercontent.com/33632578/85231926-f5cd5e80-b403-11ea-864b-a162b339ccc0.png)

**Comment by victorbucutea** [comment]
Mai incearca odata. E posibil sa nu se fi deployat ultima versiune

**Comment by ovidiu16** [comment]
Campul "parola" tot se valideaza la spatii libere.
Testat pe Chrome 83

![Passs](https://user-images.githubusercontent.com/33632578/85323794-5aa2ba80-b4d1-11ea-8c23-49065c212f0d.png)

**Comment by ovidiu16** [comment]
Campul parola este validat cu 8 spatii libere.

![Pass1](https://user-images.githubusercontent.com/33632578/85592897-3b319c00-b64f-11ea-84b7-b59f274b256c.png)

**Comment by ovidiu16** [comment]
Fixat.
![image](https://user-images.githubusercontent.com/33632578/85785966-78bb2580-b732-11ea-9650-65af4e2f70e5.png)
