### ISSUE TITLE
Pagina "Termenii si conditiile" nu este asa cum se asteapta

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#31]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Click pe linkul "termenii si conditiile" de sub campul parola

Observat
![Terms](https://user-images.githubusercontent.com/33632578/84811537-ae1a9180-b015-11ea-9af3-777e2b967e6e.png)

Asteptat
Utilizatorul ar trebui sa fie redirectionat catre o pagina unde sunt prezentati termenii si conditiile utilizarii aplicatiei.

**Comment by ovidiu16** [comment]
Daca link-ul de termeni si conditii este deschis intr-o fereastra noua, apare 
![PArc](https://user-images.githubusercontent.com/33632578/85232127-6d4fbd80-b405-11ea-9f98-8be3f2c429f4.png)

Daca lunk-ul de termeni si conditii este deschis din pagina de inregistrare dand click pe el, apare 
![loga](https://user-images.githubusercontent.com/33632578/85232143-87899b80-b405-11ea-8d80-2a485cce3f04.png)

Ar trebui sa apara o pagina cu termenii si conditiile, pagina care nu necesita logare.

**Comment by victorbucutea** [comment]
Ok, ar tb sa fie ok acum

**Comment by ovidiu16** [comment]
Fixat.
![Termss](https://user-images.githubusercontent.com/33632578/85323138-2aa6e780-b4d0-11ea-8d41-28ef7e9c7a5b.png)
