### ISSUE TITLE
Nu se poate adauga numar de telefon pe mobil

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#33]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Introdu un numar de telefon 

Observat
Numarul de telefon este adaugat, dar nu se valideaza pentru ca trebuie adaugat un spatiu intre numere. Pe mobil, daca se adauga spatiu intre numere, se sterge tot.

Asteptat
Formatul numarului de telefon ar trebui sa fie ca si pe Desktop - sa permita sa inceapa cu 7 si sa puna spatii tot dupa 3 numere.

Sugestie: Numarul de telefon ar trebui sa fie validat din 10 cifre, fara a pune automat spatiu intre ele.
![ezgif-2-3bc3052cf8a0](https://user-images.githubusercontent.com/33632578/84813617-e40d4500-b018-11ea-997b-599761e4f44b.gif)

Testat pe Huawei nova 5t.

**Comment by victorbucutea** [comment]
Ok am scos partea cu introdus doar ciffre si corectare 'as you type' . Acum e doar validare normala pe camp

**Comment by ovidiu16** [comment]
Campul nu este validat, indiferent cum se adauga numarul de telefon (cu spatii sau fara).
Posibil sa fie si de la https://github.com/victorbucutea/parking-space/issues/75
![105622005_643057139619867_3825454374616860131_n](https://user-images.githubusercontent.com/33632578/85779266-1828ea00-b72c-11ea-8a92-e82ef98b90aa.jpg)

**Comment by victorbucutea** [comment]
Ce sa zic .. asa se vede la mine. E drept ca am mai adaugat un exemplu de nr de telefon fara spatiu sa nu induc in eroare utilizatorul

<img width="531" alt="Screenshot 2020-06-25 at 23 37 42" src="https://user-images.githubusercontent.com/1927369/85792951-f421d480-b73c-11ea-883e-da31967a05ce.png">

am testat si pare sa mearga si pe chrom si pe safari.

**Comment by ovidiu16** [comment]
Fixat.
![105994499_4237033473036017_4093574410338926965_n](https://user-images.githubusercontent.com/33632578/85859275-9be2e500-b7c5-11ea-9bae-4f7452e79f8f.jpg)
