### ISSUE TITLE
Utilizatorul este redirectionat catre pagina de map search

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#34]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/login?fbLogin=user_denied
2.Click pe butonul de recuperare parola
3.Introdu o adresa de mail inregistrata pe site
4.Acceseaza mail-ul si click pe iconita "Go Park"

Observat
Utilizatorul este redirectionat catre pagina "https://go-park.ro/app/index.html?#!/map/search"

Asteptat 
Utilizatorul ar trebui sa fie redirectionat catre homepage.
![Goplink](https://user-images.githubusercontent.com/33632578/84815706-15d3db00-b01c-11ea-8f7a-b792f967ae0d.png)

**Comment by victorbucutea** [comment]
E ok asa. In fond vrem sa aducem lumea in aplicatie nu pe site :)
