### ISSUE TITLE
Headerul si footerul sunt duplicate

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#35]
1.Acceseaza https://go-park.ro/users/password/edit?email=ovidiu.ovidiu0%40gmail.com&reset_password_token=XpNw_MDWDLH6xNvC3G8j sau click pe linkul de resetare parola din mail

Observat
Header-ul si footer-ul sunt duplicate.

Asteptat
Doar un header si un footer ar trebui sa fie afisat pe pagina de resetare a parolei.
![Headf](https://user-images.githubusercontent.com/33632578/84817995-78c67180-b01e-11ea-88c6-adc9a0a205e7.png)

**Comment by victorbucutea** [comment]
E acelasi cu #50
