### ISSUE TITLE
Parola de utilizator nu poate fi schimbata

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#36]
1.Acceseaza https://go-park.ro/users/password/edit?email=ovidiu.ovidiu0%40gmail.com&reset_password_token=XpNw_MDWDLH6xNvC3G8j sau click pe link-ul de recuperare parola din mail

Observat
O eroare este afisata dupa ce utilizatorul a dat click pe butonul de "Schimba parola"

Asteptat
Parola utilizatorului ar trebui sa fie schimbata daca implineste toate cerintele (minim 8 caractere si parolele sa fie la fel in ambele campuri)
![Pass](https://user-images.githubusercontent.com/33632578/84818803-c1caf580-b01f-11ea-9ba2-b42e0af6216d.png)

**Comment by victorbucutea** [comment]
Asta e din cauza ca link-ul din email contine 'go-park.ro' . Ar tb sa modific manual in 'go-park-staging.herokuapp.com'. O sa incerc sa modific configuratia respectiva ...

**Comment by victorbucutea** [comment]
Deci nu prea pot sa modific ( cel putin nu usor) . Cel mai bine testeaza inlocuind 'go-park.ro' cu 'https://go-park-staging.herokuapp.com'

**Comment by ovidiu16** [comment]
Cu link-ul https://go-park-staging.herokuapp.com/users/password/edit?email=ovidiu.ovidiu0%40gmail.com&reset_password_token=XpNw_MDWDLH6xNvC3G8j functioneaza la parametri.
