### ISSUE TITLE
Casuta de bifat nu este vizibila la inregistrarea cu Facebook

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#37]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/login
2.Click pe butonul de Log in with Facebook
3.Log in cu un cont de Facebook care nu a mai fost inregistrat pe site

Asteptat
Casuta de bifat ar trebui sa fie afisata ca utilizatorul sa poata fi de acord cu termenii si conditiile.

![FBLo](https://user-images.githubusercontent.com/33632578/84933420-893e2100-b0de-11ea-9b9e-6b411795e4b1.png)

**Comment by victorbucutea** [comment]
Nu prea il pot reproduce. Am instalat is FF 

<img width="1069" alt="Screenshot 2020-06-21 at 16 00 19" src="https://user-images.githubusercontent.com/1927369/85225245-6d859400-b3d8-11ea-9e63-4a9e31645b36.png">

**Comment by victorbucutea** [comment]
Cred ca mai e nevoi de ceva

**Comment by ovidiu16** [comment]
Nu se mai reproduce.
![FBl](https://user-images.githubusercontent.com/33632578/85232249-404fda80-b406-11ea-82ba-213ca6c66d61.png)
