### ISSUE TITLE
O linie rosie este afisata de fiecare data cand harta se mareste sau micsoreaza

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#38]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Mareste sau micsoreaza harta

Observat
O linie rosie este afisata sub campul "cauta adresa" de fiecare data cand harta se mareste sau se micsoreaza.

Asteptat
Linia rosie nu ar trebui sa fie vizibila de fiecare data cand se mareste sau se micsoreaza harta.
![ezgif-2-de22d36ba8a9](https://user-images.githubusercontent.com/33632578/84934628-454c1b80-b0e0-11ea-9f82-eb791671e4fc.gif)

**Comment by victorbucutea** [comment]
e ok asa. Ar tb sa apara de fiecare data cand incarci ceva de pe server. E confusing ?

**Comment by ovidiu16** [comment]
Nu e confusing, e ok.
