### ISSUE TITLE
Campul de valuta se suprapune peste campul de pret

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#40]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search/
2.Click pe butonul de "Vinde"

Observat
Campul de valuta se suprapune peste campul de pret.

Asteptat
Campul de valuta nu ar trebui sa se suprapuna peste campiul de pret.
![Bani](https://user-images.githubusercontent.com/33632578/84936654-429ef580-b0e3-11ea-8885-1fa55ceb5b02.png)

**Comment by victorbucutea** [comment]
cu ce browser testezi ? Pe chrome /safari pare sa fie ok.
<img width="522" alt="Screenshot 2020-06-17 at 23 07 45" src="https://user-images.githubusercontent.com/1927369/84945045-6a945600-b0ef-11ea-826f-a47da7995b1e.png">

**Comment by ovidiu16** [comment]
Firefox 77

**Comment by ovidiu16** [comment]
Fixat.
![Date](https://user-images.githubusercontent.com/33632578/85327354-7741f100-b4d7-11ea-8468-0a37050d9f1a.png)
