### ISSUE TITLE
Eroarea campurilor nu este afisata

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#41]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe butonul vinde
3.Campurile "Titlu" si "Adresa" trebuie sa fie cu spatii libere (butonul space apasat de cel putin odata)
4.Data trebuie sa fie aleasa in trecut

Observat
Campurile se valideaza (culoarea verde) introducand spatii libere, iar data poate fi aleasa in trecut.

Asteptat
O eroare ar trebui sa fie afisata cand este apasat butonul "Urmatorul", avand campurile titlu si adresa cu spatii libere, iar adresa sa fie in trecut.

Sugestie: Data nu ar trebui sa poata fi aleasa in trecut, iar campurie nu ar trebui sa valideze spatii libere.
![Valida](https://user-images.githubusercontent.com/33632578/84940083-00c47e00-b0e8-11ea-9143-009d28c29db0.png)

**Comment by ovidiu16** [comment]
Campurile nu mai valideaza spatii libere, dar data tot se poate alege in trecut.
![Camps](https://user-images.githubusercontent.com/33632578/85327184-2f22ce80-b4d7-11ea-8c73-801675163df6.png)

**Comment by victorbucutea** [comment]
ok. Problema cu acest camp este ca ai optiunea sa editezi un spatiu care deja exista. Atunci in ecranul asta tb sa afisezi o data din trecut, nu poti bloca pentru data curenta, ca utilizatorul va crede ca s-a modificat data de inceput. Poate o solutie ar fi sa 'blochezi' data in viitor doar la adaugare de spatiu. La editare sa nu mai ai constrangerea asta. 

Tu ce zici ca ar fi cel mai bine ?

**Comment by victorbucutea** [comment]
Ok, acum exist o data minima de azi si pt momentul cand editezi un loc. In fond nu ar tb sa influenteze rezervarile active pentru periooada de valabilitate. Validarea cu intervalul de valabilitatea a spatiului s-a facut cand au fost create rezervarile. E ok pt v1.0

**Comment by ovidiu16** [comment]
Este ok acuma. Nu se poate alege data si ora din trecut.
![date1](https://user-images.githubusercontent.com/33632578/85593464-be52f200-b64f-11ea-803e-af3f78846bfb.png)
