### ISSUE TITLE
Butonul de plateste nu functioneaza

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#43]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe o parcare disponibila
3.Rezerva o parcare, dar fara a fi platita
4.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/myoffers
5.Click pe butonul de plateste

Observat
Nu se intampla nimic daca este apasat butonul de plateste.

Asteptat
Butonul de plateste ar trebui sa functioneze la fel  ca si butonul de Achita.

Sugestie – Ar trebui sa fie afisat doar un buton de Achita, nu ambele.

![Plateste](https://user-images.githubusercontent.com/33632578/85052430-91ab6000-b1a1-11ea-94d7-35878bbfeabe.png)

**Comment by victorbucutea** [comment]
Issue-ul e fixat ... insa ce parere ai despre tot spatiul asta irosit ? ... 

<img width="604" alt="Screenshot 2020-06-20 at 21 44 55" src="https://user-images.githubusercontent.com/1927369/85209298-71190c80-b33f-11ea-9e95-05946d1dfa0c.png">

**Comment by ovidiu16** [comment]
Problema inca exista.
Testat pe Firefox 77 private.
![Plata](https://user-images.githubusercontent.com/33632578/85232553-565e9a80-b408-11ea-9208-8f671a6d0f31.png)

Spatiul nu este pentru poze cu locul de parcare?
Daca utilizatorul adauga 3 poze cu locul de parcare, spatiul o sa fie cu poze.

**Comment by victorbucutea** [comment]
Intr-adevar am uitat sa il scot de la my reservations. Acum nu ar mai tb sa apara butonul, iar achitarea se face facand click pe rezervare.

**Comment by ovidiu16** [comment]
Fixat.
![Platas](https://user-images.githubusercontent.com/33632578/85322719-75742f80-b4cf-11ea-86cd-b749242aa99e.png)
