### ISSUE TITLE
Butonul de stergere se suprapune peste adresa cautata pe mobil

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#47]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Cauta o adresa in campul "Cauta adresa" (ex Calea Victoriei, București, România)

Observat
Butonul de stergere ( X ) se suprapune peste adresa cautata.

Asteptat
Butonul de stergere nu ar trebui sa se suprapuna peste adresa cautata.
![Close](https://user-images.githubusercontent.com/33632578/85057037-de466980-b1a8-11ea-88ad-81b73c46f741.png)

**Comment by victorbucutea** [comment]
Aici va tb sa facem un compromis. Daca e sa reduc spatiul cu text vizibil, se va vedea prea putin din adresa, lucru care parca nu l-as face doar ca sa nu se mai suprapuna textul. 

Avem 2 variante :
1. Sa nu mai afisez tara ( care oricum e evidenta pentru oricine foloseste applicatia ) 
2. Sa inlocuiesc butonul de menu cu cel de 'sterge' cand am text in casuta ... 

Tu pe care o preferi? Oricum il punem pt milestone 2.0, in release-ul urmator. Putem livra cu el asa. pt moment

**Comment by ovidiu16** [comment]
Prima varianta cred ca ar fi ok. (daca aplicatia o sa fie doar pe Romania)

**Comment by victorbucutea** [comment]
Gata am gasit o solutie intermediara. II punem un background semi transparent.

<img width="415" alt="Screenshot 2020-07-08 at 11 00 39" src="https://user-images.githubusercontent.com/1927369/86893417-43d3a900-c10a-11ea-81bc-856d190ea9c9.png">

**Comment by ovidiu16** [comment]
Fixat.
![X](https://user-images.githubusercontent.com/33632578/86956590-013dbb00-c162-11ea-9a0b-2e45cd879af1.png)
