### ISSUE TITLE
Rezervarea platita nu se actualizeaza automat

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#48]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe o parcare disponibila si faceti o rezervare fara a achita 
3.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/myoffers
4.Plateste rezervarea facuta

Observat
Pagina nu se actualizeaza automat din Neplatita in Platit, doar dupa reincarcarea paginii.

Asteptat
Pagina ar trebui sa se actualizeze automat dupa ce utilizatorul a platit rezervarea.
![Rezervare](https://user-images.githubusercontent.com/33632578/85058049-3762cd00-b1aa-11ea-94b3-1a386ebd7207.png)

**Comment by victorbucutea** [comment]
Ok, acum merge dar reseteaza state-ul din spatele ferestrei de play. Chiar nu avem timp sa il facem mai elegant.

**Comment by ovidiu16** [comment]
Tot dupa reincarcarea paginii apare ca si achitat. Ar trebui sa fie altcumva? Poate nu am inteles eu bine.
![ezgif-2-41aff8a1fec7](https://user-images.githubusercontent.com/33632578/85326792-83797e80-b4d6-11ea-9c79-bc6fd954ec6d.gif)

**Comment by victorbucutea** [comment]
reincearca te rog. Ar trebui sa se reincarce 'Rezervarile mele ' 
<img width="572" alt="Screenshot 2020-06-25 at 15 25 33" src="https://user-images.githubusercontent.com/1927369/85719546-3248d500-b6f8-11ea-81a7-a6858b04b15e.png">

**Comment by ovidiu16** [comment]
Problema a fost rezolvata.
![image](https://user-images.githubusercontent.com/33632578/85779856-b321c400-b72c-11ea-82c2-13de4443057a.png)
