### ISSUE TITLE
Un loc de parcare se poate adauga de mai multe ori

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#49]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe butonul de "Vinde"
3.Completeaza campurile necesare
4.Click pe butonul de "Posteaza locul" de mai multe ori

Observat
Locul de parcare se posteaza de cate ori se apasa pe butonul de "Posteaza locul".

Asteptat
Locul de parcare ar trebui sa fie postat doar o data.

Sugestie: Butonul ar trebui sa devina inactiv dupa ce a fost apasat o data, sau fereastra ar trebui sa se inchida.

Testat pe Firefox 77.
![ezgif-2-68c750067fd1](https://user-images.githubusercontent.com/33632578/85059544-7d209500-b1ac-11ea-91ec-9bcd8cd7575e.gif)

**Comment by victorbucutea** [comment]
Wth ... Devine inactiv ... Nu am reusit sa il reproduc.

**Comment by ovidiu16** [comment]
Nu se pot adauga locuri de parcare noi. O sa-l retestez dupa ce se fixeaza.
https://github.com/victorbucutea/parking-space/issues/68

**Comment by ovidiu16** [comment]
Butonul devine inactiv. Problema nu se mai reproduce.
