### ISSUE TITLE
Pagina de schimba parola nu este stilizata

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#50]
1.Acceseaza https://go-park-staging.herokuapp.com/users/password/edit?email=ovidiu.ovidiu0%40gmail.com&reset_password_token=pV-GhfPzcDMMt7yUeDh6

Observat
Pagina nu este stilizata.

Asteptat
Pagina ar trebui sa fie stilizata (Header, meniu, footer).
![Schimba](https://user-images.githubusercontent.com/33632578/85061541-a42c9600-b1af-11ea-8ec1-fc3e8ac4df2d.png)

**Comment by ovidiu16** [comment]
Problema inca exista.
Testat pe Firefox si Chrome private.
![Schimbapass](https://user-images.githubusercontent.com/33632578/85232419-780b5200-b407-11ea-879d-b4c75f80f2a8.png)

**Comment by victorbucutea** [comment]
cred ca nu era deployata ultima versiune.
<img width="1126" alt="Screenshot 2020-06-22 at 22 01 40" src="https://user-images.githubusercontent.com/1927369/85325305-11079f00-b4d4-11ea-9fb5-0f83e017af1f.png">

**Comment by ovidiu16** [comment]
Fixat.
![Schi](https://user-images.githubusercontent.com/33632578/85326106-61333100-b4d5-11ea-900a-54c683635377.png)
