### ISSUE TITLE
Poza nu este marita pe mobile

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#51]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Incarca o poza
3.Click pe poza

Observat
Poza nu este afisata.

Asteptat
Poza ar trebui sa fie afisata si pe mobile.
![ImgMobil](https://user-images.githubusercontent.com/33632578/85168982-cab40500-b273-11ea-8b14-f362a496dc13.png)

**Comment by victorbucutea** [comment]
should be ok now. 

! DE notat ca toate imaginile stocate nu. vor ffunctiona, doar cele adaugate de acum incolo. Am schimbat modul cum se stocheaza imaginile!

**Comment by ovidiu16** [comment]
Fixat.
![105015084_265846201150873_6163231100736481749_n](https://user-images.githubusercontent.com/33632578/85326033-3b0d9100-b4d5-11ea-8ab1-efcb4d7170a5.jpg)
