### ISSUE TITLE
Link-ul sau informatia lipseste de pe fereastra de info

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#53]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html?#!/map/search
2.Click pe butonul "?"
3.Click pe butonul "Am inteles"
4.Observa textul

Observat
Textul este "În funcție de perioadă si locație. Mai multe informații aici. "

Asteptat
Dupa textul "În funcție de perioadă si locație. **Mai multe informații aic**i. " ar mai trebui sa fie un link sau o informatie de unde utilizatorul sa afle mai multe informatii despre postarea unui loc de parcare.

Testat pe Firefox 77 desktop si Chrome mobile.
![104813193_313759729622130_5078891931508982770_n](https://user-images.githubusercontent.com/33632578/85170931-c4735800-b276-11ea-9960-a710f13fc2b2.jpg)

**Comment by victorbucutea** [comment]
Am scos textul cu totul. Ar fi tb sa te redirecteze la o pagina cu statistici de pret, insa nu avem pt moment asa ceva.

**Comment by ovidiu16** [comment]
Fixat.
![106017467_275723160187996_927499512669537133_n](https://user-images.githubusercontent.com/33632578/85859148-7524ae80-b7c5-11ea-88af-13e34f3487b2.jpg)
