### ISSUE TITLE
AM si PM sunt taiate pe mobile

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#56]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe butonul de vinde
3.Click pe "Orar pe zile/ore"
4.Verifica ora

Observat
AM si PM nu sunt vizibile in totalitate pe mobile.

Asteptat
AM si PM ar trebui sa fie vizibile in totalitate pe mobile.
![104768867_268412534485357_9091087821872194159_n](https://user-images.githubusercontent.com/33632578/85229811-a6336680-b3f4-11ea-979c-90add37baa9b.jpg)

**Comment by victorbucutea** [comment]
the same as #57 . O sa il pun in v2.0

**Comment by victorbucutea** [comment]
Hai sa il ascundem sub pres pe asta si il fixam cand punem in picioare feater-ul de rezervare pe intervale neregulate
