### ISSUE TITLE
Calitate slaba a imaginilor incarcate

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#61]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/search
2.Click pe butonul de vinde
3.Completeaza un loc de parcare si incarca o poza
4.Acceseaza "Locurile mele" si observa poza incarcata

Observat
Poza este destul de blurata si nu foarte clara.

Asteptat
Poza ar trebui sa fie clara, ca si cand este maximizata.
Testat pe mobile.
![104860944_1208501976150102_8432124483271063608_n](https://user-images.githubusercontent.com/33632578/85231119-51e0b480-b3fd-11ea-8f87-ac4067d3fb9d.jpg)

**Comment by victorbucutea** [comment]
poti te rog sa atasezi poza cu care ai testat ?

**Comment by ovidiu16** [comment]
Cu poza aceasta am testat.
![105946058_262634548403415_6635700541778360151_n](https://user-images.githubusercontent.com/33632578/85384912-536bc300-b54a-11ea-9d87-e9bfa00bb1c0.png)

**Comment by victorbucutea** [comment]
Da intr-adevar daca incarci o imagine mica, thumbnail-ul din lista de parcari va avea calitate slaba ( thumbnail-ul este scalat la 10 % in dimensiune, si asta implicit pierde din calitate si devine vizibil sau deranjant pentru imagini mici cum e cea din attach. 
Il voi pune pe won't fix. Daca ai o imagine mai mare care se vede prost, please remove wontfix label

**Comment by ovidiu16** [comment]
Cu o imagine mai mare (5 mb) poza se vede bine.
