### ISSUE TITLE
Locurile de parcare nu se pot sterge

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#62]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts

Observat
Locurile de parcare nu se pot sterge.

Asteptat
Locurile de parcare ar trebui sa se poata sterge, pentru ca un utilizator poate a vandut parcarea, s-a mutat sau orice alt motiv. Plus ca daca ar ramane parcari neutilizate pe harta, aceasta s-ar aglomera foarte tare.
![105455716_274446680334428_5749692804085692305_n](https://user-images.githubusercontent.com/33632578/85231257-40e47300-b3fe-11ea-9a08-780b4f14d7da.jpg)

**Comment by victorbucutea** [comment]
Se pot sterge din consola de admin, urmeaza asta :)

**Comment by victorbucutea** [comment]
Il inchidem pe asta, urmeaza sa testam si consola de admin.
