### ISSUE TITLE
Mobile: Spatiu intre elementele din sectiunea "Lista plati efectuate"

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#63]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/account/payments-received
2.Observa elementele din sectiunea "Lista plati efectuate" (daca au fost plati efectuate)

Observat
Pretul este legat de data, iar ora este legata de Authorized.

Asteptat
Spatiu ar trebui adaugat intre elementele din sectiunea "Lista plati efectuate"
Testat pe mobile.
![104709482_269393331064594_6229669727998389597_n](https://user-images.githubusercontent.com/33632578/85231355-ff07fc80-b3fe-11ea-9851-ad584ff0df12.jpg)

**Comment by victorbucutea** [comment]
Am scos link-ul 'detalii'. Acum se deschid detaliile facand click pe rand.

**Comment by ovidiu16** [comment]
Fixat.
![image](https://user-images.githubusercontent.com/33632578/85780469-5377e880-b72d-11ea-992c-662bac1de252.png)
