### ISSUE TITLE
Textul "Nu ai primit nici o plata" este afisat pentru o secunda

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#66]
1.Acceseazahttps://go-park-staging.herokuapp.com/app/index.html#!/account/payments-received
2.Verifica pe mobile si desktop

Observat
Textul "Nu ai primit nici o plata" este afisat pentru o secunda pe mobile, iar pe desktop sunt afisate mai multe bare de defilare inactive.

Asteptat
Pagina https://go-park-staging.herokuapp.com/app/index.html#!/account/payments-received ar trebui sa fie ca si celelalte pagini https://go-park-staging.herokuapp.com/app/index.html#!/account/withdrawals si https://go-park-staging.herokuapp.com/app/index.html#!/account/payments

![Lista](https://user-images.githubusercontent.com/33632578/85231696-24e2d080-b402-11ea-95c9-5a6669e0327c.png)
![105968741_958749294564401_5158628189563225433_n](https://user-images.githubusercontent.com/33632578/85231697-257b6700-b402-11ea-919a-713b5367a6da.jpg)

**Comment by ovidiu16** [comment]
Pe mobile a fost fixat.
Pe desktop inca mai sunt afisate barele de defilare. (Asa ar trebui sa fie?)
![Plati](https://user-images.githubusercontent.com/33632578/85930183-f9109080-b8c2-11ea-8529-9901563e0521.png)
![Platiprim](https://user-images.githubusercontent.com/33632578/85930184-f9a92700-b8c2-11ea-9f45-1e461f3b9bcb.png)

**Comment by victorbucutea** [comment]
Poti reincerca te rog? Nu am reusit sa il reproduc...

**Comment by ovidiu16** [comment]
Fixat.
![plati3](https://user-images.githubusercontent.com/33632578/86537348-211d7680-bef7-11ea-9cc5-a4a10f359a92.png)
