### ISSUE TITLE
Butonul de "Am inteles si sunt de acord cu conditiile" nu este vizibil in totalitate pe mobile

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#71]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Click pe link-ul de termeni si conditii

Observat
Butonul de "Am inteles si sunt de acord cu conditiile" nu este vizibil in totalitate pe mobile.

Asteptat
Butonul ar trebui sa fie mai mic, cu mai putina informatie.(Sunt de acord)

Testat pe Chrome mobile Huawei Nova 5t
![104945904_318829745947373_4776092598281270071_n](https://user-images.githubusercontent.com/33632578/85442531-ff3bff80-b598-11ea-9702-3fd31e480005.jpg)

**Comment by victorbucutea** [comment]
Am scurtat textul = Sunt de acrod cu conditiile :)

**Comment by ovidiu16** [comment]
Fixat.
![105290733_921306155020554_1006139514318391793_n](https://user-images.githubusercontent.com/33632578/85858767-d9933e00-b7c4-11ea-9708-57f96920587e.jpg)
