### ISSUE TITLE
Utilizatorul este trimis catre pagina de Log in

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#72]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Click pe link-ul de termeni si conditii
3.Accepta termenii si conditiile

Observat
Utilizatorul este redirectionat catre pagina de log in.

Asteptat
Dupa ce sunt accepati termenii si conditiile, utilizatorul ar trebui sa ramana tot pe pagina de inregistrare.
![ezgif-2-8cf0c3fa05a0](https://user-images.githubusercontent.com/33632578/85442983-6ce82b80-b599-11ea-8e63-e84eb4954cb2.gif)

**Comment by victorbucutea** [comment]
fixed.

**Comment by ovidiu16** [comment]
Fixat.
