### ISSUE TITLE
Textul este confuz la prelungirea valabilitatii unui loc de parcare

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#74]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts
2.Prelungeste valabilitatea unui loc de parcare

Observat
Am prelungit valabilitatea unui loc de parcare expirat, din 25.06 ora 20 pana in 25.06 ora 22. si mi-a aratat ca este valabil inca o zi.

Asteptat
Ar trebui sa arate "Valabil din 25.06.2020 ora 20:00 pana in 25.06.2020 ora 22:00. (sau ceva asemanator care sa nu induca utilizatorul in eroare)

![ezgif-2-503722bb2265](https://user-images.githubusercontent.com/33632578/85600975-9b780c00-b656-11ea-86dc-7e4a3ce14d64.gif)
![Valab](https://user-images.githubusercontent.com/33632578/85600982-9ca93900-b656-11ea-9175-31149e7fe911.png)

**Comment by victorbucutea** [comment]
Uff f.. 
<img width="356" alt="Screenshot 2020-06-26 at 00 04 21" src="https://user-images.githubusercontent.com/1927369/85795260-ac04b100-b740-11ea-8f70-c0d73ca2bc34.png">

**Comment by victorbucutea** [comment]
Deci chiar nu il pot reproduce ... 
<img width="352" alt="Screenshot 2020-06-26 at 00 06 33" src="https://user-images.githubusercontent.com/1927369/85795478-fbe37800-b740-11ea-8a4d-81bc1e19487b.png">

**Comment by ovidiu16** [comment]
Eu am prelungit valabilitatea de la 15 la 16 ( o ora), la mine fiind 12:26 cand am prelungit.
Arata ca este valabil inca 4 ore. Arata asa pentru ca, calculeaza ora prezenta la cat s-a facut prelungirea, adica 12:26 la mine pana la ora ce se termina, adica 16 (sunt 4 ore de la 12 la 16.)
![Valabs](https://user-images.githubusercontent.com/33632578/85842780-e6a23400-b7a8-11ea-86c4-35618351cccd.png)

**Comment by victorbucutea** [comment]
Ok acum am inteles. acum se afiseaza 'valabil in viitor'

**Comment by ovidiu16** [comment]
Fixed.
![Valviitr](https://user-images.githubusercontent.com/33632578/85929628-2f4c1100-b8bf-11ea-8782-177adbd0e998.png)
