### ISSUE TITLE
Tara nu mai este preselectata pe mobile

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#75]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/register
2.Observa tara pe mobile

Observat
Tara nu mai este preselectata atunci cand utilizatorul acceseaza pagina de inregistrare.

Asteptat
Tara ar trebui sa fie preselectata.
![106087044_3150257498354026_7601723327760353666_n](https://user-images.githubusercontent.com/33632578/85778978-ce400400-b72b-11ea-91e3-69f318a0119d.jpg)

**Comment by victorbucutea** [comment]
Se pare ca l-am introduc cand am fixat #33 . Sper sa fie ok acum . Pe mac merge.

**Comment by ovidiu16** [comment]
Fixat.
![Phon](https://user-images.githubusercontent.com/33632578/85842118-d6d62000-b7a7-11ea-9d8b-d1928e7c559d.png)
