### ISSUE TITLE
Modificarea locului de parcare

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#78]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts
2.Click pe butonul de "modifica datele locului"
3.Click pe butonul de "urmatorul"

Asteptat
Daca un utilizator isi modifica un loc de parcare, in loc de butonul de "Posteaza locul", ar trebui sa fie "Actualizeaza locul".
![Inked106524842_189263312524207_3847693473796014029_n_LI](https://user-images.githubusercontent.com/33632578/85789689-bbcbc780-b737-11ea-9480-f41d06689ef9.jpg)

**Comment by victorbucutea** [comment]
Ok, l-am redenumit in 'Salveaza '

**Comment by ovidiu16** [comment]
Fixat.
![Salv](https://user-images.githubusercontent.com/33632578/86363722-ed84e700-bc7f-11ea-913f-f1b0eb06d18d.png)
