### ISSUE TITLE
Plati efectuate pe un cont nou creat

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#79]
1.Creeaza un cont
2.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/account/payments

Observat
In sectiunea plati efectuate apar foarte multe plati.

Asteptat
Sectiunea plati efectuate ar trebui sa fie fara nici o plata daca utilizatorul este cu un cont nou si nu a facut nici o plata.
![COnt](https://user-images.githubusercontent.com/33632578/86015823-bb2e7c00-ba2a-11ea-9e7a-956f92cfe618.png)

**Comment by victorbucutea** [comment]
@ovidiu16  nu stiu cum ai reusit... Pe user-ul ovidiu.ovidiu0+10@gmail.com  nu ai nici un payment id ... deci nu ar prea avea cum sa ia payment-urile

**Comment by victorbucutea** [comment]
mmm... doar daca cumva nu s-a sters din cache utilizatorul vechi ? Ai deshis mai multe tab-uri non-incognito?

**Comment by ovidiu16** [comment]
Am facut acuma un cont nou si am foarte multe plati efectuate.
ovidiu.ovidiu0+11@gmail.com
Test1234!

![new](https://user-images.githubusercontent.com/33632578/86348382-45afef00-bc68-11ea-9689-5b5a4553083a.png)

**Comment by ovidiu16** [comment]
Fixat.
![platir](https://user-images.githubusercontent.com/33632578/86490527-56e42300-bd70-11ea-85b0-ac250118c7fb.png)
