### ISSUE TITLE
Tab-ul de Retrage banii nu este activ

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#80]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/account
2.Observa tab-ul de retrage banii

Observat
Tab-ul de Retrage banii nu este activ in momentul cand este accesata pagina de account.

Asteptat
Tab-ul de Retrage banii ar trebui sa fie activ activ in momentul cand este accesata pagina de account.
![106152883_267955844459671_4515968079032432159_n](https://user-images.githubusercontent.com/33632578/86016405-6808f900-ba2b-11ea-89d4-b2cd68190765.jpg)

**Comment by ovidiu16** [comment]
Tab-ul ramane activ.
![Tab](https://user-images.githubusercontent.com/33632578/86363562-b3b3e080-bc7f-11ea-80de-e3fe77b0b755.png)

**Comment by victorbucutea** [comment]
Right nu era fixat cum trebuie

**Comment by ovidiu16** [comment]
Fixat.
![Retr](https://user-images.githubusercontent.com/33632578/86490625-b0e4e880-bd70-11ea-94de-18239cc103ed.png)
