### ISSUE TITLE
Un utilizator poate rezerva mai multe locuri de parcare în aceeași zi

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#84]
Observat
Un utilizator poate rezerva mai multe locuri de parcare în aceeași zi cu o singura masina.

Asteptat
Un utilizator ar trebui sa poata rezerva doar un singur loc de parcare in aceeasi zi si aceleasi ore cu o masina.
![106248201_329726234695041_2353392275323957828_n](https://user-images.githubusercontent.com/33632578/86021383-b28d7400-ba31-11ea-90ca-e35ffc27189e.jpg)

**Comment by victorbucutea** [comment]
Asta e perfect normal. Daca cineva vrea sa cheltuiasca mai multi bani, nu il oprim.
