### ISSUE TITLE
Nu se intampla nimic daca este apasat pe "Click aici pentru detalii" din mail

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#87]
Rezerva un loc de parcare sau posteaza un loc de parcare

Observat
In textul din mail apare "Click aici pentru detalii", care daca este apasat, nu se intampla nimic.

![106057458_2634484026833939_2280671087198109147_n](https://user-images.githubusercontent.com/33632578/86024562-d18e0500-ba35-11ea-90d8-69717d2aec3b.jpg)
![106125457_269750777624044_7179747454123741410_n](https://user-images.githubusercontent.com/33632578/86024571-d2269b80-ba35-11ea-8a9a-bc6f6159a04e.jpg)
![83466318_275680183679100_3118351254875630278_n](https://user-images.githubusercontent.com/33632578/86024574-d2bf3200-ba35-11ea-898f-0375fa2cb811.jpg)

**Comment by victorbucutea** [comment]
Cred ca e de la clientul de mail care sterge link-ul

<img width="550" alt="Screenshot 2020-07-03 at 15 53 04" src="https://user-images.githubusercontent.com/1927369/86471111-65691500-bd45-11ea-83a4-ed2d867753fa.png">

**Comment by victorbucutea** [comment]
on second thought e posibil sa nu functioneze pt c anu are protocolul setat in url

**Comment by ovidiu16** [comment]
Fixat.
![Click](https://user-images.githubusercontent.com/33632578/86491883-ccea8900-bd74-11ea-93ad-76324ca7f229.png)
