### ISSUE TITLE
Pretul total al unui loc de parcare difera

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#89]
Rezerva un loc de parcare si observa pretul in fereastra de "Plateste", in rezervarile mele, in mail si in mesaj.

Observat
In fereastra "Plateste" apare 159.72 RON
In rezervarile mele si in mail apare 120 RON
In mesaj apare 145.2 RON

Asteptat
Pretul total ar trebui sa fie la fel sau cel putin sa contina informatii de ce este diferit.
![106457850_2395044557455045_4172281055436211194_n](https://user-images.githubusercontent.com/33632578/86129096-da8cde00-baea-11ea-9fc6-8d9d3955f859.jpg)
![79212084_571108490241099_3940168859199662813_n](https://user-images.githubusercontent.com/33632578/86129101-dbbe0b00-baea-11ea-970e-bda2f5096634.jpg)
![106428075_904382136713784_198701632393934856_n](https://user-images.githubusercontent.com/33632578/86129103-dbbe0b00-baea-11ea-9de6-e5c0b594786d.jpg)
![106211153_270511887357234_1474400141833394342_n](https://user-images.githubusercontent.com/33632578/86129108-dcef3800-baea-11ea-8e79-fe857653a433.jpg)

**Comment by victorbucutea** [comment]
Da ar tb sa fie mai explicit ...

**Comment by victorbucutea** [comment]
Ideea e ca peste tot ar tb sa apara 120 Ron ( cu exceptia ecranului de plata unde este stipulat comisionul ). Asta a fost costul parcarii si banii pe care ii primeste proprietarul in cont. Daca vrei sa verifici sumele platite ai meniul de plati.

**Comment by victorbucutea** [comment]
Am modificat si in sms ul de confirmare a rezervarii apare suma efectiva pe care o primeste proprietarul - 120 ron.

**Comment by ovidiu16** [comment]
Fixat.
![107699776_596968241212156_3576558048516160508_n](https://user-images.githubusercontent.com/33632578/86537660-84100d00-bef9-11ea-9f8e-9f14c92028fc.jpg)
![banu](https://user-images.githubusercontent.com/33632578/86537704-ce918980-bef9-11ea-947d-7bd90bd5b36a.png)
