### ISSUE TITLE
Rezervarea anulata nu scade din banii castigati

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#90]
1.Rezerva un loc de parcare de pe un cont
2.Mergi pe contul care are locul de parcare
3.Observa ca s-au adaugat banii pe rezervare
4.Anuleaza rezervarea

Observat
Rezervarea anulata nu scade din banii castigati.

Asteptat
Rezervarea anulata ar trebui sa scada din banii castigati, iar banii ar trebui sa se intoarca la cel care a inchiriat locul.
![rezanulata](https://user-images.githubusercontent.com/33632578/86248248-5011b080-bbb6-11ea-8662-887289ef833d.png)

**Comment by victorbucutea** [comment]
Pai nu ar trebui sa scada. Ar trebui doar sa nu ii poti retrage ( sunt venituri in asteptare )

**Comment by victorbucutea** [comment]
Suma de acolo poate afisa banii castigati total. Daca nu e un alt issue legat de asta da-i close.

**Comment by ovidiu16** [comment]
Banii ar trebui retrasi din soldul in asteptare. Momentan nu sunt retrasi daca se anueaza o oferta.
![ezgif-2-cd585282b83e](https://user-images.githubusercontent.com/33632578/86538082-6c865380-befc-11ea-8219-d4867dc613ad.gif)

**Comment by victorbucutea** [comment]
Ouch. Asta e dureroos. Mai ramane si problema returnarii banilor pt rezervarile anulate. Dar asta o sa fie manuala pt moment

**Comment by ovidiu16** [comment]
Banii sunt retrasi de la soldul in asteptare din https://go-park-staging.herokuapp.com/app/index.html#!/account/withdraw dar mai sunt afisati in https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts la "Ati castigat in total" si "Aveti in cont"
![locm](https://user-images.githubusercontent.com/33632578/86959577-bbcfbc80-c166-11ea-8c3c-03f7e1b4645f.png)
![acc](https://user-images.githubusercontent.com/33632578/86959580-bd00e980-c166-11ea-8f6e-b5a5008bf322.png)
![re2](https://user-images.githubusercontent.com/33632578/86959582-bd00e980-c166-11ea-92b2-fe6724a2bcae.png)
![Rezv](https://user-images.githubusercontent.com/33632578/86959583-bd998000-c166-11ea-9b51-32d19bcbbaf6.png)

**Comment by victorbucutea** [comment]
Pai e ok asa. Acolo arata banii castigati. Ca o parte din ei vor intra peste mai mult ( daca nu se anuleaza o rezervare ) e acceptabil dpdv functioonal.

**Comment by victorbucutea** [comment]
Daca nu e alt issue pe partea asta, il pooti inchide.

**Comment by ovidiu16** [comment]
Pai asta este problema in https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts , se face o rezervare si banii din asteptare sunt adaugati la banii castigati si sunt afisati in Locurile mele. Daca o rezervare se anuleaza, nu se mai scade si din totalul din Locurile mele. (Arata tot suma totala dinainte de anularea rezervarii)

**Comment by victorbucutea** [comment]
right. Acum am inteles.

**Comment by ovidiu16** [comment]
Banii nu se scad din soldul disponibil si din "Aveti in cont".
La https://go-park-staging.herokuapp.com/app/index.html#!/account/payments-received ar trebui sa fie taiat si afisat butonul de anulat daca a fost anulata rezervarea (ca si la "Locurile mele")
![Sold](https://user-images.githubusercontent.com/33632578/87338470-ebf3d280-c54d-11ea-9ccc-d0836a8e5a2e.png)

**Comment by victorbucutea** [comment]
Pai e ok. 'Aveti in cont' din pagina de Locurile mele iti arata banii pe care ii ai minus cei in asteptare - in alte cuvinte arata doar banii ce pot fi retrasi.


<img width="537" alt="Screenshot 2020-07-14 at 17 30 41" src="https://user-images.githubusercontent.com/1927369/87438064-c02d2700-c5f7-11ea-8b65-fa2dd233262e.png">


In asteptare usesr-ul are 145 Ron:
<img width="481" alt="Screenshot 2020-07-14 at 17 32 04" src="https://user-images.githubusercontent.com/1927369/87438225-f10d5c00-c5f7-11ea-80a2-9801986c6cbe.png">

**Comment by victorbucutea** [comment]
Poate ar fi mai bine ca in pagina 'locurile mele' sa arate si banii in asteptare... insa e sufficient pt mooment dk asa cum e merge.

**Comment by ovidiu16** [comment]
In imaginea atasata de mine am fost cu un cont nou. Am postat un loc de parcare, locul a fost rezervat cu 240 lei.
Banii au aparut in cont. Am anulat rezervarea si normal ar fi ca sa am sold disponibil 0 si la aveti in cont tot 0 pentru ca nu am castigat nimic daca am anulat rezervarea.
Daca este ok asa cum este acuma, o sa inchid ticketul :)

**Comment by victorbucutea** [comment]
Da, cred ca e o problema 🥇

**Comment by victorbucutea** [comment]
ok, acum ar tb sa calculeze ok si in cazul anularilor, si in cazul banilor care nu ssunt inca disponibili

**Comment by ovidiu16** [comment]
Apare eroarea "Unprocessable Entity" atunci cand vreau sa anulez o rezervare.

**Comment by victorbucutea** [comment]
Poti sa mai incerci odata ? Cred ca nu era executat un script.

**Comment by ovidiu16** [comment]
Este ok acuma.
