### ISSUE TITLE
TVA la plati efectuate

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#97]
1.Acceseaza https://go-park-staging.herokuapp.com/app/index.html#!/account/payments
2.Observa sectiunea de TVA

Observat
La TVA apare 25.2N si 2.52N

Asteptat
"N" ar trebui sa apara?
![Tvca](https://user-images.githubusercontent.com/33632578/86819973-10086d00-c091-11ea-81cb-a0c8cccd6506.png)

**Comment by victorbucutea** [comment]
Nu ar trebui sa apara N... Insa nu ar trebui sa apara nici parcare intre _2020-07-02 00:00:00 si 2020-07-02 00:00:00_

**Comment by ovidiu16** [comment]
"N" nu mai apare la TVA si nici data in format 00:00:00.
Data apare gresit. Apare  2020-07-08 21:30:37 - 2020-07-08 21:30:37 pe cand ar trebui sa apara  2020-07-08 21:30:37 - 2020-07-09 21:30:37 (Apare data cand s-a facut rezervarea de doua ori)
![rez3](https://user-images.githubusercontent.com/33632578/86958867-7eb6fa80-c165-11ea-8b7c-c28647b335f5.png)
![TVa](https://user-images.githubusercontent.com/33632578/86958869-7f4f9100-c165-11ea-968e-6e060699e608.png)

**Comment by victorbucutea** [comment]
Dap, era o greseala. fac push acum.

**Comment by ovidiu16** [comment]
Fixat.
![Dat](https://user-images.githubusercontent.com/33632578/87077237-8345e680-c22b-11ea-831d-e544e064a342.png)
