### ISSUE TITLE
Locul de parcare este postat, dar utilizatorul este redirectionat

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#98]
1.Posteaza un loc de parcare la o adresa
2.Reincarca pagina

Observat
Utilizatorul este trimis catre alta adresa.

Asteptat
Utilizatorul ar trebui sa fie tot la adresa cautata (adresa unde a postat locul de parcare) si sa-i fie afisat locul de parcare.
*Locul de parcare ar trebui sa fie afisat pe harta fara sa fie nevoie de reincarcarea paginii*
![ezgif-2-976f5850aa3b](https://user-images.githubusercontent.com/33632578/87079878-66131700-c22f-11ea-90f8-b5c88fa4b450.gif)

**Comment by victorbucutea** [comment]
Harta ar tb pozitioneaza in locul in care raspunde browser-ul la locatia curenta.  Daca ai refuzat sa iti dezvalui locatia, atunci esti pozitionat la niste coordonate default. De asemenea ai butonul de centrare pe locatie, cum as putea sa il fac mai vizibil ?
However, ma gandesc acum ca poate ar fi bine ca dupa un refresh sa te pozitioneze la ultima locatie ... Sau dupa un nou login, sa te readuca la coordonatele ultimei locatii. 

Crezi ca ar fi ceva util?

**Comment by ovidiu16** [comment]
Poate ca utilizatorul ar trebui sa fie dus la locurile lui de parcare postate (daca are locuri postate). Daca are mai multe, sa fie dus la unul dintre ele. (pentru log in).
Daca nu are loc postat, sa fie dus la o ultima locatie sau sa ii ceara permisiunea de a accesa locatia lui curenta.(pentru log in).
Iar daca utilizatroul este logat, ar fi ok ca dupa refresh sa-l pozitioneze la ultima locatie.

**Comment by victorbucutea** [comment]
Deci dupa login redirectionam utilizatorul in ordinea asta:
0. Rezervarea urmatoare ( daca exista una in urm 2-3 zile )  
1. Centrare pe locatia curenta ( cu acceptare info locatii ) - ma gandesc ca ar fi util dat fiind ca deschizi aplicatia sa cauti un loc in jur, nu ? 
2. Unul din locurile postate
3. Ultima locatie la care a folosit aplicatia ( asta ca sa evitam sa il aducem in tineretului de fiecare data 👍 )

**Comment by ovidiu16** [comment]
Pe mine tot pe tineretului m-a redirectionat dupa ce am postat un loc de parcare si am dat refresh, dupa ce am rezervat un loc de parcare si am intrat iarasi in aplicatie si cand am intrat fara a avea o rezervare.

**Comment by victorbucutea** [comment]
Pai nu e implementat inca :)

dum., 12 iul. 2020, 6:10 PM Cimpan Ovidiu <notifications@github.com> a
scris:

**Comment by ovidiu16** [comment]
Oo, Ok :)

**Comment by victorbucutea** [comment]
Bun , deci acum :

1. Dupa search in ecranul principal, dupa login sau inrgisstrare esti redirectionat la adresa cautata
2. Daca ai o rezervare, te centreaza pe coordonatele spatiului
3. Daca nu e nici una din cele de mai sus, esti pozitionat la ultima locatie -  ma gandesc vor fi mult mai multi care utilizeaza pur si spl decat cei care posteaza loc si chiar si astia din urma pot rezerva sau cauta alte locuri.

**Comment by ovidiu16** [comment]
Pe mine m-a centrat de fiecare data la ultimul loc cautat (unde am ramas pe harta inainte de log out)
Testat pe Chrome si Firefox.

**Comment by ovidiu16** [comment]
E ok daca utilizatorul se logheaza si nu are cache. Daca intra pentru prima data pe un browser si se logheaza il duce la rezervarea in curs.
Cumva ar trebui sa fie asa de fiecare data, indiferent daca utilizatorul a mai folosit browser-ul pentru aplicatie sau nu.

**Comment by victorbucutea** [comment]
_Cumva ar trebui sa fie asa de fiecare data, indiferent daca utilizatorul a mai folosit browser-ul pentru aplicatie sau nu._
Pai daca a rezervat inseamna ca a folosit aplicatia. Daca are rezervare confirmata, atunci e dus la rezerrvare, daca nu e dus la ultima locatie. 

Asa ar tb sa functioneze:
Dupa search in ecranul principal, dupa login sau inrgisstrare esti redirectionat la adresa cautata
Daca a intrat direct prin ecranul de login ( nu a cautat din pagina principala ) si e la prima acceare a aplicatiei este dus la o locatie default ( tineretului ).

**Comment by ovidiu16** [comment]
Am inteles. Este ok acuma.
