### ISSUE TITLE
Poza locului de parcare nu este afisata

### ISSUE THREAD

**Issue by ovidiu16** [victorbucutea/parking-space#99]
1.Modifica un loc de parcare care are poza

Observat
Poza nu este afisata. (este afisat doar numele pozei si o iconita de document)

Asteptat
Poza ar trebui sa fie afisata.
![Poz](https://user-images.githubusercontent.com/33632578/87081062-5f859f00-c231-11ea-8626-c2c676bca0bc.png)

**Comment by victorbucutea** [comment]
Nu prea reusesc sa o reproduc. Ai facut un ctrl+f5. ?

<img width="430" alt="Screenshot 2020-07-09 at 22 37 15" src="https://user-images.githubusercontent.com/1927369/87083120-bfca1000-c234-11ea-8cc9-0ebd56bb3603.png">

**Comment by ovidiu16** [comment]
Se poate reproduce pe Firefox 78 https://go-park-staging.herokuapp.com/app/index.html#!/map/myposts , click pe butonul "Modifica datele locului" (locul de parcare trebuie sa fie cu poza)

**Comment by victorbucutea** [comment]
Ai dat de cateva ori refresh nu? Ideea e ca aplicatia utilizeaza un service worker, care face cache la tot ce inseamna js, html. Asta pentru a rula mai rapid si mai bine pe mobile cand semnalul este prost ( ai putea testa si asta daca ai ocazia ) . Toate site-urile mari folosesc tehnologia asta. 

Revenind la pb, e putin pb ca doar pe ff sa nu se reproduca..

**Comment by ovidiu16** [comment]
Cred ca este de la Firefox. Pe Chrome si Edge se vede poza atasata. 
![Locimg](https://user-images.githubusercontent.com/33632578/87249776-c68d9880-c469-11ea-96ca-259591d02112.png)
